// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkUeH95G7X39AMZxeOR2wqMC7zMSdHJfw',
    appId: '1:405535222210:web:4adf766f2a2aa1c3fc0e5b',
    messagingSenderId: '405535222210',
    projectId: 'stockit-defda',
    authDomain: 'stockit-defda.firebaseapp.com',
    storageBucket: 'stockit-defda.appspot.com',
    measurementId: 'G-WF8N272PJB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrIhWODDaXJMhKs6PNUNboaHbz6KdjP3k',
    appId: '1:405535222210:android:24cc0af42f6f46cafc0e5b',
    messagingSenderId: '405535222210',
    projectId: 'stockit-defda',
    storageBucket: 'stockit-defda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkmTI_OqVEiAgy2xHWX1sskOO0-8uoFiw',
    appId: '1:405535222210:ios:623179a48f758b78fc0e5b',
    messagingSenderId: '405535222210',
    projectId: 'stockit-defda',
    storageBucket: 'stockit-defda.appspot.com',
    iosBundleId: 'com.example.stockit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkmTI_OqVEiAgy2xHWX1sskOO0-8uoFiw',
    appId: '1:405535222210:ios:623179a48f758b78fc0e5b',
    messagingSenderId: '405535222210',
    projectId: 'stockit-defda',
    storageBucket: 'stockit-defda.appspot.com',
    iosBundleId: 'com.example.stockit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkUeH95G7X39AMZxeOR2wqMC7zMSdHJfw',
    appId: '1:405535222210:web:b81b843f0f7e3be5fc0e5b',
    messagingSenderId: '405535222210',
    projectId: 'stockit-defda',
    authDomain: 'stockit-defda.firebaseapp.com',
    storageBucket: 'stockit-defda.appspot.com',
    measurementId: 'G-XDRMQHVNHM',
  );
}
